/*
 * generated by Xtext
 */
package com.br.terra.dcl.serializer;

import com.br.terra.dcl.dCL.BasicType;
import com.br.terra.dcl.dCL.Can;
import com.br.terra.dcl.dCL.Cannot;
import com.br.terra.dcl.dCL.DCDecl;
import com.br.terra.dcl.dCL.DCLComponent;
import com.br.terra.dcl.dCL.DCLComponentInterface;
import com.br.terra.dcl.dCL.DCLLayer;
import com.br.terra.dcl.dCL.DCLModule;
import com.br.terra.dcl.dCL.DCLPackage;
import com.br.terra.dcl.dCL.DCLSubSystem;
import com.br.terra.dcl.dCL.EntityType;
import com.br.terra.dcl.dCL.InterfaceType;
import com.br.terra.dcl.dCL.Model;
import com.br.terra.dcl.dCL.Must;
import com.br.terra.dcl.dCL.Only;
import com.br.terra.dcl.dCL.Only2;
import com.br.terra.dcl.services.DCLGrammarAccess;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class DCLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DCLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DCLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DCLPackage.BASIC_TYPE:
				sequence_BasicType(context, (BasicType) semanticObject); 
				return; 
			case DCLPackage.CAN:
				sequence_Can(context, (Can) semanticObject); 
				return; 
			case DCLPackage.CANNOT:
				sequence_Cannot(context, (Cannot) semanticObject); 
				return; 
			case DCLPackage.DC_DECL:
				sequence_DCDecl(context, (DCDecl) semanticObject); 
				return; 
			case DCLPackage.DCL_COMPONENT:
				sequence_DCLComponent(context, (DCLComponent) semanticObject); 
				return; 
			case DCLPackage.DCL_COMPONENT_INTERFACE:
				sequence_DCLComponentInterface(context, (DCLComponentInterface) semanticObject); 
				return; 
			case DCLPackage.DCL_LAYER:
				sequence_DCLLayer(context, (DCLLayer) semanticObject); 
				return; 
			case DCLPackage.DCL_MODULE:
				sequence_DCLModule(context, (DCLModule) semanticObject); 
				return; 
			case DCLPackage.DCL_SUB_SYSTEM:
				sequence_DCLSubSystem(context, (DCLSubSystem) semanticObject); 
				return; 
			case DCLPackage.ENTITY_TYPE:
				sequence_EntityType(context, (EntityType) semanticObject); 
				return; 
			case DCLPackage.INTERFACE_TYPE:
				sequence_InterfaceType(context, (InterfaceType) semanticObject); 
				return; 
			case DCLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case DCLPackage.MUST:
				sequence_Must(context, (Must) semanticObject); 
				return; 
			case DCLPackage.ONLY:
				sequence_Only(context, (Only) semanticObject); 
				return; 
			case DCLPackage.ONLY2:
				sequence_Only2(context, (Only2) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ElementType returns BasicType
	 *     BasicType returns BasicType
	 *
	 * Constraint:
	 *     (typeName='access' | typeName='declare' | typeName='handle' | typeName='create' | typeName='depend')
	 */
	protected void sequence_BasicType(ISerializationContext context, BasicType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Can returns Can
	 *
	 * Constraint:
	 *     can='can-'
	 */
	protected void sequence_Can(ISerializationContext context, Can semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.CAN__CAN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.CAN__CAN));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCanAccess().getCanCanKeyword_0(), semanticObject.getCan());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Cannot returns Cannot
	 *
	 * Constraint:
	 *     cannot='cannot-'
	 */
	protected void sequence_Cannot(ISerializationContext context, Cannot semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.CANNOT__CANNOT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.CANNOT__CANNOT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCannotAccess().getCannotCannotKeyword_0(), semanticObject.getCannot());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DCDecl returns DCDecl
	 *
	 * Constraint:
	 *     (
	 *         (only=Only t=[DCLStructureElement|ID] can=Can elementType=ElementType type=[DCLStructureElement|ID]) | 
	 *         (t=[DCLStructureElement|ID] cannot=Cannot elementType=ElementType type=[DCLStructureElement|ID]) | 
	 *         (t=[DCLStructureElement|ID] can=Can elementType=ElementType type=[DCLStructureElement|ID]) | 
	 *         (t=[DCLStructureElement|ID] can=Can elementType=ElementType only2=Only2 type=[DCLStructureElement|ID]) | 
	 *         (t=[DCLStructureElement|ID] must=Must entityType=EntityType type=[DCLStructureElement|ID])
	 *     )
	 */
	protected void sequence_DCDecl(ISerializationContext context, DCDecl semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DCLStructureElement returns DCLComponentInterface
	 *     DCLComponentInterface returns DCLComponentInterface
	 *
	 * Constraint:
	 *     (name=ID component=[DCLStructureElement|ID] interfaceType=InterfaceType)
	 */
	protected void sequence_DCLComponentInterface(ISerializationContext context, DCLComponentInterface semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.DCL_STRUCTURE_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.DCL_STRUCTURE_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.DCL_COMPONENT_INTERFACE__COMPONENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.DCL_COMPONENT_INTERFACE__COMPONENT));
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.DCL_COMPONENT_INTERFACE__INTERFACE_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.DCL_COMPONENT_INTERFACE__INTERFACE_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDCLComponentInterfaceAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDCLComponentInterfaceAccess().getComponentDCLStructureElementIDTerminalRuleCall_3_0_1(), semanticObject.getComponent());
		feeder.accept(grammarAccess.getDCLComponentInterfaceAccess().getInterfaceTypeInterfaceTypeParserRuleCall_4_2_0(), semanticObject.getInterfaceType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DCLStructureElement returns DCLComponent
	 *     DCLComponent returns DCLComponent
	 *
	 * Constraint:
	 *     (name=ID (layer=[DCLStructureElement|ID] | subSystem=[DCLStructureElement|ID])?)
	 */
	protected void sequence_DCLComponent(ISerializationContext context, DCLComponent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DCLStructureElement returns DCLLayer
	 *     DCLLayer returns DCLLayer
	 *
	 * Constraint:
	 *     (name=ID level=INT (layer=[DCLStructureElement|ID] | subSystem=[DCLStructureElement|ID] | component=[DCLStructureElement|ID])?)
	 */
	protected void sequence_DCLLayer(ISerializationContext context, DCLLayer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DCLStructureElement returns DCLModule
	 *     DCLModule returns DCLModule
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_DCLModule(ISerializationContext context, DCLModule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.DCL_STRUCTURE_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.DCL_STRUCTURE_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDCLModuleAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DCLStructureElement returns DCLSubSystem
	 *     DCLSubSystem returns DCLSubSystem
	 *
	 * Constraint:
	 *     (name=ID subSystem=[DCLStructureElement|ID]?)
	 */
	protected void sequence_DCLSubSystem(ISerializationContext context, DCLSubSystem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementType returns EntityType
	 *     EntityType returns EntityType
	 *
	 * Constraint:
	 *     (entity='extend' | entity='implement' | entity='derive' | entity='throw' | entity='useannotation')
	 */
	protected void sequence_EntityType(ISerializationContext context, EntityType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     InterfaceType returns InterfaceType
	 *
	 * Constraint:
	 *     (interfaceTypeName='provided' | interfaceTypeName='required')
	 */
	protected void sequence_InterfaceType(ISerializationContext context, InterfaceType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (structureElements+=DCLStructureElement+ dCDecl+=DCDecl*)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Must returns Must
	 *
	 * Constraint:
	 *     must='must-'
	 */
	protected void sequence_Must(ISerializationContext context, Must semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.MUST__MUST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.MUST__MUST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMustAccess().getMustMustKeyword_0(), semanticObject.getMust());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Only2 returns Only2
	 *
	 * Constraint:
	 *     only2='-only'
	 */
	protected void sequence_Only2(ISerializationContext context, Only2 semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.ONLY2__ONLY2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.ONLY2__ONLY2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOnly2Access().getOnly2OnlyKeyword_0(), semanticObject.getOnly2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Only returns Only
	 *
	 * Constraint:
	 *     only='only'
	 */
	protected void sequence_Only(ISerializationContext context, Only semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DCLPackage.Literals.ONLY__ONLY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DCLPackage.Literals.ONLY__ONLY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOnlyAccess().getOnlyOnlyKeyword_0(), semanticObject.getOnly());
		feeder.finish();
	}
	
	
}
