/*
 * generated by Xtext
 */
package com.br.terra.dcl.ui.contentassist

import com.br.terra.dcl.ui.contentassist.AbstractDCLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DCLProposalProvider extends AbstractDCLProposalProvider {
}
