/*
 * generated by Xtext
 */
package com.br.terra.dcl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DCLRuntimeModule extends com.br.terra.dcl.AbstractDCLRuntimeModule {

}
