/*
* generated by Xtext
*/
package com.br.terra.dcl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DCLStandaloneSetup extends DCLStandaloneSetupGenerated{

	public static void doSetup() {
		new DCLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

