/*
 * generated by Xtext
 */
package com.br.terra.dcl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DCLUiModule extends com.br.terra.dcl.ui.AbstractDCLUiModule {
	public DCLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
